---
driver:
  name: ec2
  instance_type: c1.xlarge
  aws_ssh_key_id: kayako-dev_ap-southeast-1_nirbhab
  require_chef_omnibus: true
  subnet_id: "subnet-93a962e4"
  security_group_ids: ["sg-03a62366"]
  region: ap-southeast-1
  availability_zone: ap-southeast-1a
  require_chef_omnibus: true
  associate_public_ip: true
  interface: public

provisioner:
  name: chef_solo

transport:
  username: root
  ssh_key: ~/.ssh/kayako-dev_ap-southeast-1_nirbhab.pem
  connection_timeout: 10
  connection_retries: 5

platforms:
  - name: "RightImage_CentOS_6.5_x64_v14.1.3.1_EBS"
    driver:
      image_id: "ami-00caeb52"
  - name: "RightImage_CentOS_5.9_x64_v12.11.4_EBS"
    driver:
      image_id: "ami-86b5fdd4"
suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum-epel::default]
      - recipe[build-essential::default]
      - recipe[ohai::default]
      - recipe[php::default]
    attributes: {
      "php" : {
        "force_compile" : true
      }
    }
